package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const defaultAPIBaseURL = "https://asyntai.com"

// asyntaiClient talks to the Asyntai chat API.
type asyntaiClient struct {
	baseURL string
	apiKey  string
	http    *http.Client
}

func newAsyntaiClient(baseURL, apiKey string) *asyntaiClient {
	base := strings.TrimSpace(baseURL)
	if base == "" {
		base = defaultAPIBaseURL
	}
	base = strings.TrimSuffix(base, "/")

	return &asyntaiClient{
		baseURL: base,
		apiKey:  strings.TrimSpace(apiKey),
		// Answers are generated by a language model, so allow for a slow one,
		// but never hang a Mattermost worker for longer than this.
		http: &http.Client{Timeout: 60 * time.Second},
	}
}

type chatRequest struct {
	Message   string `json:"message"`
	SessionID string `json:"session_id,omitempty"`
	WebsiteID int    `json:"website_id,omitempty"`
}

type chatResponse struct {
	Success  bool   `json:"success"`
	Response string `json:"response"`
	Error    string `json:"error"`
}

// ask sends one question and returns the answer text.
func (c *asyntaiClient) ask(message, sessionID string, websiteID int) (string, error) {
	if c.apiKey == "" {
		return "", fmt.Errorf("no API key is set")
	}

	body, err := json.Marshal(chatRequest{
		Message:   message,
		SessionID: sessionID,
		WebsiteID: websiteID,
	})
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest(http.MethodPost, c.baseURL+"/api/v1/chat/", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.apiKey)
	req.Header.Set("User-Agent", "Asyntai-Mattermost-Plugin/1.0")

	resp, err := c.http.Do(req)
	if err != nil {
		return "", fmt.Errorf("could not reach Asyntai: %w", err)
	}
	defer resp.Body.Close()

	// Cap the body. A runaway response should not eat the server's memory.
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", err
	}

	var parsed chatResponse
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return "", fmt.Errorf("unexpected reply from Asyntai (HTTP %d)", resp.StatusCode)
	}

	if !parsed.Success || parsed.Response == "" {
		if parsed.Error != "" {
			return "", fmt.Errorf("%s", parsed.Error)
		}
		return "", fmt.Errorf("Asyntai returned no answer (HTTP %d)", resp.StatusCode)
	}

	return parsed.Response, nil
}
